### ISSUE TITLE
Subtitle are not Getting displayed

### ISSUE THREAD

**Issue by MilapKundalia** [nriccar/react-native-subtitles#6]
I was trying this library to display subtitles for Audio but subtitles are not getting displayed 
below is the code snippet I have used. Let me know if I have missed anything. I think it's unable to parse the subtitle file.

```
 <Subtitles
                    {...{ currentTime }}
                    selectedsubtitle={{
                        file: 'https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt',
                    }}
                />
```

**Comment by nriccar** [comment]
Can you share a reproducible example? Also, try to put the Subtitle component as low as possible related to its siblings
